### ISSUE TITLE
Allow for custom highlight color

### ISSUE THREAD

**Issue by Hacksore** [benbalter/github-mention-highlighter#11]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

The color is not the most friendly so allowing an override is ideal.

### Describe the solution you'd like

Allow for the use of a custom highlight color through some means of configuration.

### Describe alternatives you've considered

Dealing with the yellow is not quite ideal :)

### Additional context

N/A

**Comment by bir-star** [comment]
> ### Is your feature request related to a problem? Please describe the problem you're trying to solve.
> The color is not the most friendly so allowing an override is ideal.
> 
> ### Describe the solution you'd like
> Allow for the use of a custom highlight color through some means of configuration.
> 
> ### Describe alternatives you've considered
> Dealing with the yellow is not quite ideal :)
> 
> ### Additional context
> N/A
