### ISSUE TITLE
Add screenshot to the Chrome webstore

### ISSUE THREAD

**Issue by Turbo87** [benbalter/github-mention-highlighter#4]
https://chrome.google.com/webstore/detail/github-mention-highlighte/ojclbekffnkgbacniibdebdihhgenlkp seems to be missing screenshots

**Comment by benbalter** [comment]
This should be fixed momentarily:

![screen shot 2015-04-01 at 4 45 43 pm](https://cloud.githubusercontent.com/assets/282759/6952248/994e4ce2-d88e-11e4-96c5-e3ecd7adc52a.png)
